config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'videos#index'
  resources :videos, only: [:index, :new, :show, :create] do
    member do
      get :status
    end
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
require 'content_disposition'

class Video < ApplicationRecord
  include ClipUploader::Attachment.new(:clip)

  validates :gif_url, presence: true
  validates :youtube_url, presence: true

  scope :ready, -> { where(status: 'ready') }

  def self.from_gifsound_params(params)
    gif_url = if params[:gfycat]
                "https://giant.gfycat.com/#{params[:gfycat]}.mp4"
              elsif params[:gifv]
                "https://i.imgur.com/#{params[:gifv]}.mp4"
              else params[:gif]
                params[:gif]
              end

    find_or_initialize_by(
      gif_url: gif_url,
      youtube_url: "https://www.youtube.com/watch?v=#{params[:v]}",
      audio_start_delay: params[:s].blank? ? 0 : params[:s]
    )
  end

  def audio_start_delay
    read_attribute(:audio_start_delay) || 0
  end

  def ready?
    status == 'ready'
  end

  def error?
    status == 'error'
  end

  def attributes
    {
      id: id,
      created_at: created_at,
      updated_at: updated_at,
      status: status,
      clip_url: clip_url,
    }
  end

  def download_url
    clip.url({ response_content_disposition: ContentDisposition.format(disposition: 'attachment', filename: "implosion-#{id}.mp4") })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    if params[:v]
      @video = Video.from_gifsound_params(gifsound_params)
      if @video.save
        ProcessVideoJob.perform_later(@video.id)
        redirect_to video_path(@video)
      end
    else
      @videos = Video.ready.order(created_at: :desc).limit(10)
    end
  end

  def new
    @video = Video.new
  end

  def show
    @video = Video.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @video }
    end
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      ProcessVideoJob.perform_later(@video.id)
      redirect_to video_path(@video)
    else
      render :new
    end
  end

  private

  def gifsound_params
    params.slice(:gif, :v, :s, :gfycat, :gifv)
  end

  def video_params
    params.require(:video).permit(:youtube_url, :gif_url, :audio_start_delay)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>imploder</title>
    <%= csrf_meta_tags %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application' %>

    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <%= favicon_link_tag 'favicons/favicon-16x16.png', rel: 'icon', type: 'image/png', sizes: '16x16' %>
    <%= favicon_link_tag 'favicons/favicon-32x32.png', rel: 'icon', type: 'image/png', sizes: '32x32' %>

    <%= yield :head %>
  </head>

  <body>
    <div id="container">
      <header>
        <h1>
          <%= link_to 'imploder', root_path, title: 'go home' %>
        </h1>
      </header>

      <div id="main-outer">
        <main>
          <%= yield %>
        </main>
      </div>

      <footer>
        <ul>
          <li>
            built by <a href="https://twitter.com/waltz" title="big on the internet">@waltz</a>
          </li>
          <li>
            see the <a href="https://github.com/waltz/imploder" title="oh god don't judge me">the source</a>
          </li>
        </ul>
      </footer>
    </div>
  </body>
</html>

app/views/videos/index.html.erb
<p>Welcome to the best gif tool in the world.</p>

<div id="homepage">
  <%= link_to 'Create an Implosion', new_video_path %>

  <div class="implosions">
    <% if @videos.nil? %>
      <p>No videos yet.</p>
    <% else %>
      <% @videos.each do |video| %>
        <div class="implosion">
          <%= link_to video_path(video) do %>
            <% if video.clip %>
              <%= image_tag video.clip(:homepage).url %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<p>Build a new implosion! Find a GIF and a Video from YouTube and we'll
combine them.</p>

<div class="composer">
  <%= form_for @video do |f| %>
    <div class="composer__field">
      <%= f.label :gif_url, 'Gif Url' %>
      <%= f.text_field :gif_url, class: 'composer__text-input' %>
    </div>

    <div class="composer__field">
      <%= f.label :youtube_url, 'Youtube Url' %>
      <%= f.text_field :youtube_url, class: 'composer__text-input' %>
    </div>

    <div class="composer__field">
      <%= f.label :audio_start_delay, 'Audio Start Delay' %>
      <%= f.text_field :audio_start_delay, class: 'composer__text-input' %>
    </div>

    <%= f.submit 'Implode!', class: 'composer__submit' %>
  <% end %>
</div>

app/views/videos/show.html.erb
<% if @video.ready? %>
  <% content_for :head do %>
    <meta name="description" content="GIF +++ YouTube Mashup!" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Check out this clip!" />
    <meta name="twitter:site" content="@imploderxyz" />
    <meta name="twitter:image" content="<%= @video.clip(:twitter).url %>" />
  <% end %>
<% end %>

<% if !@video.ready? %>
  <div id="video-fetcher" data-video-id=<%= @video.id %>>
    <p>Making your video. Hold tight!</p>
    <%= image_tag 'spinner.gif', class: 'spinner' %>
  </div>
<% end %>

<% if @video.error? %>
  <p>Drat, sorry, something went wrong when making your video.</p>
<% end %>

<% if @video.ready? %>
  <video id="video-player" autoplay loop controls>
    <source src="<%= @video.clip_url %>" type="video/mp4">
  </video>
  <ul id="video-links">
    <li><%= link_to 'Download', @video.download_url %></li>
    <li><%= link_to 'Tweet', "https://twitter.com/intent/tweet?text=#{URI.encode('love it')}&url=#{video_url(@video)}", class: 'tweet-link', target: 'blank' %></li>
  </ul>
<% end %>